name: flutter_bluetooth_serial_ble
version: 0.5.0
description: A basic Flutter Bluetooth Serial library
authors:
  - Eduardo Folly <edufolly@gmail.com>
  - Martin Mauch <martin.mauch@gmail.com>
  - Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
  - Erhannis glued in BLE code from kai-morich's https://github.com/kai-morich/SimpleBluetoothLeTerminal and uploaded it as a new library
homepage: https://github.com/Erhannis/flutter_bluetooth_serial_ble
repository: https://github.com/Erhannis/flutter_bluetooth_serial_ble
issue_tracker: https://github.com/edufolly/flutter_bluetooth_serial/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
